# Site settings
title: "Farhan Saad Ahmed"
email: "fsa787@gmail.com"
description: > # this means to ignore newlines until "baseurl:"
baseurl: "farhansaad.github.io" # the subpath of your site, e.g. /blog/
url: "farhansaad.github.io" # the base hostname & protocol for your site

twitter_username: "@fsa787"
github_username: "farhansaad"

# Build settings
markdown: kramdown
